import { Skeleton } from '@devlog/components';
import { cn } from '@devlog/utils';

export const PostItemLoading = () => {
  return (
    <div
      className={cn(
        'block',
        'px-4 md:px-10',
        'py-6 md:py-12',
        'text-white',
        'h-[220px]',
        'cursor-pointer',
      )}
    >
      <div
        className={cn(
          'flex',
          'justify-stretch',
          'items-center',
          'gap-2',
          'mb-3',
        )}
      >
        <Skeleton
          height={26}
          variant='rectangular'
          width={26}
        />
        <Skeleton
          height={28}
          width='100%'
        />
      </div>
      <Skeleton
        className={cn('mb-6')}
        height={24}
        width='100%'
      />
      <div
        className={cn(
          'flex',
          'justify-between',
          'items-center',
          'gap-2',
        )}
      >
        <Skeleton
          height={20}
          width={80}
        />
        <div
          className={cn(
            'flex',
            'justify-end',
            'items-center',
            'gap-3',
          )}
        >
          <Skeleton
            height={20}
            width={80}
          />
          |
          <div
            className={cn(
              'flex',
              'justify-start',
              'items-center',
              'gap-2',
            )}
          >
            <Skeleton
              height={14}
              variant='circular'
              width={14}
            />
            <Skeleton
              height={20}
              width={30}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
