import type { Metadata } from 'next';

import { Header } from '@devlog/components';

import './globals.css';
import '@devlog/ui-config';
import localFont from 'next/font/local';

const pretandard = localFont({
  src: './fonts/PretendardVariable.woff2',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={pretandard.className}
      lang='ko'
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
