import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './globals.css';
import '@devlog/ui-config';
import { Header } from '@devlog/components';
import localFont from 'next/font/local';

import { QueryProvider } from '@/providers/QueryProvider';

const pretandard = localFont({
  src: './fonts/PretendardVariable.woff2',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      className={pretandard.className}
      lang='ko'
    >
      <body>
        <QueryProvider>
          <Header />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
